/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.xputil.util.db;


import fyi.sorenneedscoffee.xputil.util.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in s4_starbot2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s4_starbot2.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
