/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.listeners.chains.db.tables.records;


import fyi.sorenneedscoffee.derg_zero.listeners.chains.db.tables.ScriptMeta;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScriptMetaRecord extends UpdatableRecordImpl<ScriptMetaRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 264123880;

    /**
     * Setter for <code>s4_starbot2.script_meta.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>s4_starbot2.script_meta.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>s4_starbot2.script_meta.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>s4_starbot2.script_meta.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ScriptMeta.SCRIPT_META.NAME;
    }

    @Override
    public Field<String> field2() {
        return ScriptMeta.SCRIPT_META.VALUE;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getValue();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getValue();
    }

    @Override
    public ScriptMetaRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public ScriptMetaRecord value2(String value) {
        setValue(value);
        return this;
    }

    @Override
    public ScriptMetaRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ScriptMetaRecord
     */
    public ScriptMetaRecord() {
        super(ScriptMeta.SCRIPT_META);
    }

    /**
     * Create a detached, initialised ScriptMetaRecord
     */
    public ScriptMetaRecord(String name, String value) {
        super(ScriptMeta.SCRIPT_META);

        set(0, name);
        set(1, value);
    }
}
