/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.moderation.db.tables;


import fyi.sorenneedscoffee.derg_zero.moderation.db.Indexes;
import fyi.sorenneedscoffee.derg_zero.moderation.db.Keys;
import fyi.sorenneedscoffee.derg_zero.moderation.db.S4D0Users;
import fyi.sorenneedscoffee.derg_zero.moderation.db.tables.records.ModerationCasesRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * @author SorenNeedsCoffee (github.com/sorenneedscoffee)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ModerationCases extends TableImpl<ModerationCasesRecord> {

    public static final ModerationCases MODERATION_CASES = new ModerationCases();
    private static final long serialVersionUID = 524784924;
    public final TableField<ModerationCasesRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    public final TableField<ModerationCasesRecord, Timestamp> CREATION_TIME = createField(DSL.name("creation_time"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");
    public final TableField<ModerationCasesRecord, String> USER_ID = createField(DSL.name("user_id"), org.jooq.impl.SQLDataType.VARCHAR(18), this, "");
    public final TableField<ModerationCasesRecord, Integer> OFFENSE_ID = createField(DSL.name("offense_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");
    public final TableField<ModerationCasesRecord, String> ADDITIONAL_COMMENTS = createField(DSL.name("additional_comments"), org.jooq.impl.SQLDataType.VARCHAR(2000), this, "");

    public ModerationCases() {
        this(DSL.name("moderation_cases"), null);
    }

    public ModerationCases(String alias) {
        this(DSL.name(alias), MODERATION_CASES);
    }

    public ModerationCases(Name alias) {
        this(alias, MODERATION_CASES);
    }

    private ModerationCases(Name alias, Table<ModerationCasesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ModerationCases(Name alias, Table<ModerationCasesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ModerationCases(Table<O> child, ForeignKey<O, ModerationCasesRecord> key) {
        super(child, key, MODERATION_CASES);
    }

    @Override
    public Class<ModerationCasesRecord> getRecordType() {
        return ModerationCasesRecord.class;
    }

    @Override
    public Schema getSchema() {
        return S4D0Users.S4_D0_USERS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MODERATION_CASES_MODERATION_CASES_OFFENSE_TYPES_ID_FK, Indexes.MODERATION_CASES_PRIMARY);
    }

    @Override
    public Identity<ModerationCasesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MODERATION_CASES;
    }

    @Override
    public UniqueKey<ModerationCasesRecord> getPrimaryKey() {
        return Keys.KEY_MODERATION_CASES_PRIMARY;
    }

    @Override
    public List<UniqueKey<ModerationCasesRecord>> getKeys() {
        return Arrays.<UniqueKey<ModerationCasesRecord>>asList(Keys.KEY_MODERATION_CASES_PRIMARY);
    }

    @Override
    public ModerationCases as(String alias) {
        return new ModerationCases(DSL.name(alias), this);
    }

    @Override
    public ModerationCases as(Name alias) {
        return new ModerationCases(alias, this);
    }

    @Override
    public ModerationCases rename(String name) {
        return new ModerationCases(DSL.name(name), null);
    }

    @Override
    public ModerationCases rename(Name name) {
        return new ModerationCases(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Timestamp, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
