/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.db;


import fyi.sorenneedscoffee.derg_zero.db.tables.Script;
import fyi.sorenneedscoffee.derg_zero.db.tables.ScriptMeta;
import fyi.sorenneedscoffee.derg_zero.db.tables.records.ScriptMetaRecord;
import fyi.sorenneedscoffee.derg_zero.db.tables.records.ScriptRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>s4_d0_script</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ScriptRecord> KEY_SCRIPT_PRIMARY = UniqueKeys0.KEY_SCRIPT_PRIMARY;
    public static final UniqueKey<ScriptMetaRecord> KEY_SCRIPT_META_PRIMARY = UniqueKeys0.KEY_SCRIPT_META_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<ScriptRecord> KEY_SCRIPT_PRIMARY = Internal.createUniqueKey(Script.SCRIPT, "KEY_script_PRIMARY", Script.SCRIPT.INDEX);
        public static final UniqueKey<ScriptMetaRecord> KEY_SCRIPT_META_PRIMARY = Internal.createUniqueKey(ScriptMeta.SCRIPT_META, "KEY_script_meta_PRIMARY", ScriptMeta.SCRIPT_META.NAME);
    }
}
