/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.moderation.db.tables.records;


import fyi.sorenneedscoffee.derg_zero.moderation.db.tables.KickList;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * @author SorenNeedsCoffee (github.com/sorenneedscoffee)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class KickListRecord extends UpdatableRecordImpl<KickListRecord> implements Record1<String> {

    private static final long serialVersionUID = -1436817543;

    public KickListRecord() {
        super(KickList.KICK_LIST);
    }

    public KickListRecord(String id) {
        super(KickList.KICK_LIST);

        set(0, id);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public String getId() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    public void setId(String value) {
        set(0, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return KickList.KICK_LIST.ID;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String value1() {
        return getId();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public KickListRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public KickListRecord values(String value1) {
        value1(value1);
        return this;
    }
}
