/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.moderation.db.tables.records;


import fyi.sorenneedscoffee.derg_zero.moderation.db.tables.ModerationCases;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModerationCasesRecord extends UpdatableRecordImpl<ModerationCasesRecord> implements Record5<Integer, Timestamp, String, Integer, String> {

    private static final long serialVersionUID = -1874180970;

    /**
     * Setter for <code>s4_d0_users.moderation_cases.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>s4_d0_users.moderation_cases.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>s4_d0_users.moderation_cases.creation_time</code>.
     */
    public void setCreationTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>s4_d0_users.moderation_cases.creation_time</code>.
     */
    public Timestamp getCreationTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>s4_d0_users.moderation_cases.user_id</code>.
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>s4_d0_users.moderation_cases.user_id</code>.
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>s4_d0_users.moderation_cases.offense_id</code>.
     */
    public void setOffenseId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>s4_d0_users.moderation_cases.offense_id</code>.
     */
    public Integer getOffenseId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>s4_d0_users.moderation_cases.additional_comments</code>.
     */
    public void setAdditionalComments(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>s4_d0_users.moderation_cases.additional_comments</code>.
     */
    public String getAdditionalComments() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Timestamp, String, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Timestamp, String, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ModerationCases.MODERATION_CASES.ID;
    }

    @Override
    public Field<Timestamp> field2() {
        return ModerationCases.MODERATION_CASES.CREATION_TIME;
    }

    @Override
    public Field<String> field3() {
        return ModerationCases.MODERATION_CASES.USER_ID;
    }

    @Override
    public Field<Integer> field4() {
        return ModerationCases.MODERATION_CASES.OFFENSE_ID;
    }

    @Override
    public Field<String> field5() {
        return ModerationCases.MODERATION_CASES.ADDITIONAL_COMMENTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Timestamp component2() {
        return getCreationTime();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public Integer component4() {
        return getOffenseId();
    }

    @Override
    public String component5() {
        return getAdditionalComments();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Timestamp value2() {
        return getCreationTime();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public Integer value4() {
        return getOffenseId();
    }

    @Override
    public String value5() {
        return getAdditionalComments();
    }

    @Override
    public ModerationCasesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ModerationCasesRecord value2(Timestamp value) {
        setCreationTime(value);
        return this;
    }

    @Override
    public ModerationCasesRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public ModerationCasesRecord value4(Integer value) {
        setOffenseId(value);
        return this;
    }

    @Override
    public ModerationCasesRecord value5(String value) {
        setAdditionalComments(value);
        return this;
    }

    @Override
    public ModerationCasesRecord values(Integer value1, Timestamp value2, String value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModerationCasesRecord
     */
    public ModerationCasesRecord() {
        super(ModerationCases.MODERATION_CASES);
    }

    /**
     * Create a detached, initialised ModerationCasesRecord
     */
    public ModerationCasesRecord(Integer id, Timestamp creationTime, String userId, Integer offenseId, String additionalComments) {
        super(ModerationCases.MODERATION_CASES);

        set(0, id);
        set(1, creationTime);
        set(2, userId);
        set(3, offenseId);
        set(4, additionalComments);
    }
}
