/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.garbagecan.moderation.db;


import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.KickList;
import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.ModerationCases;
import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.NonoWords;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4D0Users extends SchemaImpl {

    private static final long serialVersionUID = -1699117298;

    /**
     * The reference instance of <code>s4_d0_users</code>
     */
    public static final S4D0Users S4_D0_USERS = new S4D0Users();

    /**
     * The table <code>s4_d0_users.kick_list</code>.
     */
    public final KickList KICK_LIST = fyi.sorenneedscoffee.garbagecan.moderation.db.tables.KickList.KICK_LIST;

    /**
     * The table <code>s4_d0_users.moderation_cases</code>.
     */
    public final ModerationCases MODERATION_CASES = fyi.sorenneedscoffee.garbagecan.moderation.db.tables.ModerationCases.MODERATION_CASES;

    /**
     * The table <code>s4_d0_users.nono_words</code>.
     */
    public final NonoWords NONO_WORDS = fyi.sorenneedscoffee.garbagecan.moderation.db.tables.NonoWords.NONO_WORDS;

    /**
     * No further instances allowed
     */
    private S4D0Users() {
        super("s4_d0_users", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            KickList.KICK_LIST,
            ModerationCases.MODERATION_CASES,
            NonoWords.NONO_WORDS);
    }
}
