/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.garbagecan.moderation.db;


import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.KickList;
import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.ModerationCases;
import fyi.sorenneedscoffee.garbagecan.moderation.db.tables.NonoWords;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in s4_d0_users
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s4_d0_users.kick_list</code>.
     */
    public static final KickList KICK_LIST = KickList.KICK_LIST;

    /**
     * The table <code>s4_d0_users.moderation_cases</code>.
     */
    public static final ModerationCases MODERATION_CASES = ModerationCases.MODERATION_CASES;

    /**
     * The table <code>s4_d0_users.nono_words</code>.
     */
    public static final NonoWords NONO_WORDS = NonoWords.NONO_WORDS;
}
