/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.starbot2.listeners.chains.db;


import fyi.sorenneedscoffee.starbot2.listeners.chains.db.tables.Script;
import fyi.sorenneedscoffee.starbot2.listeners.chains.db.tables.ScriptMeta;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S4Starbot2 extends SchemaImpl {

    private static final long serialVersionUID = 505650976;

    /**
     * The reference instance of <code>s4_starbot2</code>
     */
    public static final S4Starbot2 S4_STARBOT2 = new S4Starbot2();

    /**
     * The table <code>s4_starbot2.script</code>.
     */
    public final Script SCRIPT = Script.SCRIPT;

    /**
     * The table <code>s4_starbot2.script_meta</code>.
     */
    public final ScriptMeta SCRIPT_META = ScriptMeta.SCRIPT_META;

    /**
     * No further instances allowed
     */
    private S4Starbot2() {
        super("s4_starbot2", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Script.SCRIPT,
            ScriptMeta.SCRIPT_META);
    }
}
