/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.db.tables;


import fyi.sorenneedscoffee.derg_zero.db.Indexes;
import fyi.sorenneedscoffee.derg_zero.db.Keys;
import fyi.sorenneedscoffee.derg_zero.db.S4D0Script;
import fyi.sorenneedscoffee.derg_zero.db.tables.records.ScriptRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Script extends TableImpl<ScriptRecord> {

    private static final long serialVersionUID = -13371378;

    /**
     * The reference instance of <code>s4_d0_script.script</code>
     */
    public static final Script SCRIPT = new Script();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScriptRecord> getRecordType() {
        return ScriptRecord.class;
    }

    /**
     * The column <code>s4_d0_script.script.index</code>.
     */
    public final TableField<ScriptRecord, Integer> INDEX = createField(DSL.name("index"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>s4_d0_script.script.value</code>.
     */
    public final TableField<ScriptRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>s4_d0_script.script</code> table reference
     */
    public Script() {
        this(DSL.name("script"), null);
    }

    /**
     * Create an aliased <code>s4_d0_script.script</code> table reference
     */
    public Script(String alias) {
        this(DSL.name(alias), SCRIPT);
    }

    /**
     * Create an aliased <code>s4_d0_script.script</code> table reference
     */
    public Script(Name alias) {
        this(alias, SCRIPT);
    }

    private Script(Name alias, Table<ScriptRecord> aliased) {
        this(alias, aliased, null);
    }

    private Script(Name alias, Table<ScriptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Script(Table<O> child, ForeignKey<O, ScriptRecord> key) {
        super(child, key, SCRIPT);
    }

    @Override
    public Schema getSchema() {
        return S4D0Script.S4_D0_SCRIPT;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCRIPT_PRIMARY);
    }

    @Override
    public UniqueKey<ScriptRecord> getPrimaryKey() {
        return Keys.KEY_SCRIPT_PRIMARY;
    }

    @Override
    public List<UniqueKey<ScriptRecord>> getKeys() {
        return Arrays.<UniqueKey<ScriptRecord>>asList(Keys.KEY_SCRIPT_PRIMARY);
    }

    @Override
    public Script as(String alias) {
        return new Script(DSL.name(alias), this);
    }

    @Override
    public Script as(Name alias) {
        return new Script(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Script rename(String name) {
        return new Script(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Script rename(Name name) {
        return new Script(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
