/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.starbot2.listeners.chains.db.tables;


import fyi.sorenneedscoffee.starbot2.listeners.chains.db.Indexes;
import fyi.sorenneedscoffee.starbot2.listeners.chains.db.Keys;
import fyi.sorenneedscoffee.starbot2.listeners.chains.db.S4Starbot2;
import fyi.sorenneedscoffee.starbot2.listeners.chains.db.tables.records.ScriptMetaRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ScriptMeta extends TableImpl<ScriptMetaRecord> {

    private static final long serialVersionUID = -579936224;

    /**
     * The reference instance of <code>s4_starbot2.script_meta</code>
     */
    public static final ScriptMeta SCRIPT_META = new ScriptMeta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ScriptMetaRecord> getRecordType() {
        return ScriptMetaRecord.class;
    }

    /**
     * The column <code>s4_starbot2.script_meta.name</code>.
     */
    public final TableField<ScriptMetaRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>s4_starbot2.script_meta.value</code>.
     */
    public final TableField<ScriptMetaRecord, String> VALUE = createField(DSL.name("value"), org.jooq.impl.SQLDataType.VARCHAR(512), this, "");

    /**
     * Create a <code>s4_starbot2.script_meta</code> table reference
     */
    public ScriptMeta() {
        this(DSL.name("script_meta"), null);
    }

    /**
     * Create an aliased <code>s4_starbot2.script_meta</code> table reference
     */
    public ScriptMeta(String alias) {
        this(DSL.name(alias), SCRIPT_META);
    }

    /**
     * Create an aliased <code>s4_starbot2.script_meta</code> table reference
     */
    public ScriptMeta(Name alias) {
        this(alias, SCRIPT_META);
    }

    private ScriptMeta(Name alias, Table<ScriptMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private ScriptMeta(Name alias, Table<ScriptMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ScriptMeta(Table<O> child, ForeignKey<O, ScriptMetaRecord> key) {
        super(child, key, SCRIPT_META);
    }

    @Override
    public Schema getSchema() {
        return S4Starbot2.S4_STARBOT2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SCRIPT_META_PRIMARY);
    }

    @Override
    public UniqueKey<ScriptMetaRecord> getPrimaryKey() {
        return Keys.KEY_SCRIPT_META_PRIMARY;
    }

    @Override
    public List<UniqueKey<ScriptMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<ScriptMetaRecord>>asList(Keys.KEY_SCRIPT_META_PRIMARY);
    }

    @Override
    public ScriptMeta as(String alias) {
        return new ScriptMeta(DSL.name(alias), this);
    }

    @Override
    public ScriptMeta as(Name alias) {
        return new ScriptMeta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ScriptMeta rename(String name) {
        return new ScriptMeta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ScriptMeta rename(Name name) {
        return new ScriptMeta(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
