/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.listeners.chains.db;


import fyi.sorenneedscoffee.derg_zero.listeners.chains.db.tables.Script;
import fyi.sorenneedscoffee.derg_zero.listeners.chains.db.tables.ScriptMeta;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in s4_starbot2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s4_starbot2.script</code>.
     */
    public static final Script SCRIPT = Script.SCRIPT;

    /**
     * The table <code>s4_starbot2.script_meta</code>.
     */
    public static final ScriptMeta SCRIPT_META = ScriptMeta.SCRIPT_META;
}
