/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.xputil.db;


import fyi.sorenneedscoffee.xputil.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in s4_d0_users
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>s4_d0_users.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
