/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.derg_zero.moderation.db;


import fyi.sorenneedscoffee.derg_zero.moderation.db.tables.KickList;
import fyi.sorenneedscoffee.derg_zero.moderation.db.tables.ModerationCases;

import javax.annotation.Generated;


/**
 * @author SorenNeedsCoffee (github.com/sorenneedscoffee)
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    public static final KickList KICK_LIST = KickList.KICK_LIST;

    public static final ModerationCases MODERATION_CASES = ModerationCases.MODERATION_CASES;
}
